# KONFIGURASI JARINGAN & INTERFACE
PHYSICAL_INTERFACE_IN="enp1s0"
PHYSICAL_INTERFACE_EXPAND="false"

# Kosongkan atau isi "false" jika tidak menggunakan Open vSwitch.
# IP statis akan otomatis diterapkan ke PHYSICAL_INTERFACE_IN.
OVS_BRIDGE="false"

SEARCH_DOMAIN="localhost.local"
