# KONFIGURASI JARINGAN & INTERFACE OVS
PHYSICAL_INTERFACE_IN="enp1s0"
# Biarkan kosong ("") atau isi "false" jika server hanya memiliki 1 port LAN
PHYSICAL_INTERFACE_EXPAND=""
OVS_BRIDGE="ovsbr0"
SEARCH_DOMAIN="meaningfrost.my.id"
