# KONFIGURASI JARINGAN & INTERFACE OVS
PHYSICAL_INTERFACE_IN="enp1s0"
PHYSICAL_INTERFACE_EXPAND=""          # Biarkan kosong ("") atau isi "false" jika hanya 1 port
OVS_BRIDGE="ovsbr0"
SEARCH_DOMAIN="meaningfrost.my.id"