#!/bin/bash
echo "================================================================="
echo "       AUTO-STATIC-IP MANAGER (v0.0.0.2-beta)"
echo "================================================================="
echo "Pengelola DHCP-ke-Statis Universal untuk Node/Host Ubuntu."
echo ""
echo "PERINTAH YANG TERSEDIA:"
echo "  start     : Menangkap IP dari DHCP ke systemd-networkd."
echo "  trigger   : Digunakan oleh udev untuk event hot-plug."
echo "  sync      : Menyelaraskan ulang Netplan dari interface.conf."
echo "  info      : Menampilkan diagnostik jaringan secara lengkap."
echo "  help      : Menampilkan layar panduan ini."
echo "================================================================="
