#!/bin/bash
echo "================================================================="
echo "       AUTO-STATIC-IP & OVS MANAGER (v0.0.0.1-beta)"
echo "================================================================="
echo "Aplikasi pengelola DHCP-ke-Statis untuk Node/Host Ubuntu."
echo ""
echo "PENGGUNAAN:"
echo "  auto-static-ip [perintah]"
echo ""
echo "PERINTAH YANG TERSEDIA:"
echo "  start     : Menangkap IP dari DHCP ke systemd-networkd."
echo "  trigger   : Digunakan oleh udev untuk event hot-plug."
echo "  sync      : Menyelaraskan ulang Netplan dari interface.conf."
echo "  info      : Menampilkan diagnostik jaringan secara lengkap."
echo "  help      : Menampilkan layar panduan ini."
echo "================================================================="
